notejam/rubyonrails/notejam/config/routes.rb
Rails.application.routes.draw do

  post 'pads/:id/edit' => 'pads#edit'

  get 'pads/:id/delete' => 'pads#delete', as: :delete_pad
  post 'pads/:id/delete' => 'pads#delete'

  get 'pads/create' => 'pads#create', as: :create_pad
  post 'pads/create' => 'pads#create'

  resources :pads, only: [:edit, :show]

  get 'notes/create' => 'notes#create', as: :create_note
  post 'notes/create' => 'notes#create'

  post 'notes/:id/edit' => 'notes#edit'

  get 'notes/:id/delete' => 'notes#delete', as: :delete_note
  post 'notes/:id/delete' => 'notes#delete'

  resources :notes, only: [:edit, :show, :index]

  get 'signup/' => 'users#signup', as: :signup
  post 'signup/' => 'users#signup'

  get 'signin/' => 'users#signin', as: :signin
  post 'signin/' => 'users#signin'

  get 'settings/' => 'users#settings', as: :settings
  post 'settings/' => 'users#settings'

  get 'signout/' => 'users#signout', as: :signout

  get 'forgot-password/' => 'users#forgot_password', as: :forgot_password
  post 'forgot-password/' => 'users#forgot_password'

  root "notes#index"

end

notejam/rubyonrails/notejam/app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :pad
  belongs_to :user
  validates :name, presence: true
  validates :text, presence: true
end

notejam/rubyonrails/notejam/app/models/pad.rb
class Pad < ActiveRecord::Base
  belongs_to :user
  has_many :notes
  validates :name, presence: true
end

notejam/rubyonrails/notejam/app/models/user.rb
class User < ActiveRecord::Base
  has_many :pads
  has_many :notes
  validates :email, presence: true,
                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i },
                    uniqueness: true
  validates :password, presence: true
  has_secure_password
end

notejam/rubyonrails/notejam/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def authenticate_user
    if session[:user_id]
      return true
    else
      redirect_to signin_path, flash: { success: 'Please sign in' }
      false
    end
  end

  private

  def not_found
    render nothing: true, status: :not_found
  end

  def order_param
    order = params[:order] || '-updated_at'
    { 'name' => 'name ASC',
      '-name' => 'name DESC',
      'updated_at' => 'updated_at ASC',
      '-updated_at' => 'updated_at DESC' }[order]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

notejam/rubyonrails/notejam/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user
  def index
    @notes = current_user.notes.order(order_param)
  end

  def edit
    @note = current_user.notes.find(params[:id])
    @current_name = @note.name
    if params[:note]
      # @TODO weird solution
      if params[:note][:pad_id] != '0'
        current_user.pads.find(params[:note][:pad_id])
      end
      if @note.update(note_params)
        redirect_to note_path(id: @note.id), flash: { success: 'Note is successfully updated' }
      end
    end
  end

  def delete
    @note = current_user.notes.find(params[:id])
    if request.post?
      @note.destroy
      redirect_to notes_path, flash: { success: 'Note is successfully deleted' }
    end
  end

  def create
    if params[:note]
      # @TODO weird solution
      if params[:note][:pad_id] != '0'
        current_user.pads.find(params[:note][:pad_id])
      end
      @note = current_user.notes.create(note_params)
      if @note.valid?
        redirect_to notes_path, flash: { success: 'Note is successfully created' }
      end
    end
  end

  def show
    @note = current_user.notes.find(params[:id])
  end

  private

  def note_params
    params.require(:note).permit(:name, :text, :pad_id)
  end
end

notejam/rubyonrails/notejam/app/controllers/pads_controller.rb
class PadsController < ApplicationController
  before_action :authenticate_user
  def create
    if params[:pad]
      @pad = Pad.new(pad_params.merge(user: current_user))
      if @pad.save
        redirect_to url_for(:notes), flash: { success: 'Pad is successfully created' }
      end
    end
  end

  def edit
    @pad = current_user.pads.find(params[:id])
    @current_name = @pad.name
    if params[:pad]
      if @pad.update(pad_params)
        redirect_to pad_path(id: @pad.id), flash: { success: 'Pad is successfully updated' }
      end
    end
  end

  def delete
    @pad = current_user.pads.find(params[:id])
    if request.post?
      @pad.destroy
      redirect_to notes_path, flash: { success: 'Pad is successfully deleted' }
    end
  end

  def show
    @pad = current_user.pads.find(params[:id])
    @notes = @pad.notes.order(order_param)
  end

  private

  def pad_params
    params.require(:pad).permit(:name)
  end
end

notejam/rubyonrails/notejam/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:settings]

  def signup
    if params[:user]
      @user = User.new(user_params)
      if @user.valid?
        @user.save
        redirect_to signin_path, flash: { success: 'Account is created. Now you can sign in.' }
      end
    end
  end

  def signin
    if request.post?
      user = User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to notes_path, flash: { success: 'Successfully signed in' }
      else
        flash.now[:error] = 'Invalid email or password'
      end
    end
  end

  def forgot_password
    if request.post?
      user = User.find_by_email(params[:email])
      if user
        new_password = generate_password
        user.password = new_password
        user.password_confirmation = new_password
        user.save
        UserMailer.send_new_password(user, new_password).deliver
        redirect_to signin_path, flash: { success: 'New password sent to your mail' }
        return
      end
      flash.now[:error] = 'No user with given email found'
    end
  end

  def signout
    session[:user_id] = nil
    redirect_to signin_path
  end

  def settings
    @user = current_user
    if params[:user]
      unless current_user.authenticate(params[:current_password])
        flash.now[:error] = 'Invalid current password'
        return
      end
      @user.password = user_params[:password]
      @user.password_confirmation = user_params[:password_confirmation]
      if @user.valid?
        @user.save
        redirect_to settings_path, flash: { success: 'Password is successfully changed' }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
  end

  def generate_password
    # weak password generation
    ('a'..'z').to_a.sample(8).join
  end
end

notejam/rubyonrails/notejam/app/helpers/application_helper.rb
module ApplicationHelper
  def field_errors(field, model)
    if model && model.errors[field].any?
      [
        "<ul class='errorlist'>",
        model.errors[field].map { |message| "<li>#{field} #{message}</li>" }.join,
        '</ul>'
      ].join.html_safe
    end
  end
end

notejam/rubyonrails/notejam/app/helpers/note_helper.rb
module NoteHelper
  def smart_date(datetime)
    diff = Date.today - datetime.to_date
    days = diff.to_i
    if days == 0
      'Today at ' + datetime.strftime('%H:%M')
    elsif days == 1
      'Yesterday'
    elsif days > 1 && days <= 7
      days.to_s + ' days ago'
    else
      datetime.strftime('%d %b %Y')
    end
  end
end

notejam/rubyonrails/notejam/app/helpers/pad_helper.rb
module PadHelper
end

notejam/rubyonrails/notejam/app/helpers/user_helper.rb
module UserHelper
end

notejam/rubyonrails/notejam/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

  <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title><%= yield(:page_title) %></title>
  <meta name="description" content="Notejam, Ruby on Rails">
  <meta name="author" content="komarserjio@gmail.com">

  <!-- Mobile Specific Metas
  ================================================== -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- CSS
  ================================================== -->
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

  <!-- csrf token
  ================================================== -->
  <%= csrf_meta_tags %>

  <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <div class="container">
    <div class="sixteen columns">
      <div class="sign-in-out-block">
        <% if current_user %>
          <%= current_user.email %>:&nbsp; <%= link_to "Account Settings", settings_path %>&nbsp;&nbsp;&nbsp;<a href="<%= url_for(:signout) %>">Sign out</a>
        <% else %>
          <a href="<%= signin_path %>">Sign In</a>&nbsp;&nbsp;&nbsp;<a href="<%= url_for(:signup) %>">Sign Up</a>
        <% end %>
      </div>
    </div>
    <div class="sixteen columns">
      <h1 class="bold-header">
        <a href="<%= url_for(:notes) %>" class="header">note<span class="jam">jam: </span></a>
        <span><%= yield(:page_title) %></span>
      </h1>
    </div>
    <% if content_for?(:pad_menu) %>
      <%= yield(:pad_menu) %>
    <% else %>
      <div class="three columns">
        <h4 id="logo">My pads</h4>
        <nav>
        <% if current_user && current_user.pads.count.nonzero? %>
          <ul>
            <% current_user.pads.each do |pad| -%>
              <li><%= link_to pad.name, pad_path(:id => pad.id) %></li>
            <% end -%>
          </ul>
        <% else %>
          <p class="empty">No pads</p>
        <% end %>
        <hr />
        <a href="<%= url_for(:create_pad) %>">New pad</a>
        </nav>
      </div>
    <% end %>
    <div class="<% if content_for?(:content_class) %><%= yield(:content_class) %><% else %>thirteen<% end %> columns content-area">
      <div class="alert-area">
        <% flash.each do |name, msg| -%>
          <div class="alert alert-<%= name %>"><%= msg %></div>
        <% end -%>
      </div>
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
    <hr class="footer" />
    <div class="footer">
      <div>Notejam: <strong>Ruby on Rails</strong> application</div>
      <div><a href="https://github.com/komarserjio/notejam">Github</a>, <a href="https://twitter.com/komarserjio">Twitter</a>, created by <a href="https://github.com/komarserjio/">Serhii Komar</a></div>
    </div>
  </div><!-- container -->
  <a href="https://github.com/komarserjio/notejam"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>
</body>
</html>

notejam/rubyonrails/notejam/app/views/layouts/users.html.erb
<% content_for :content_class do %>sixteen<% end %>
<% content_for :pad_menu do %><!-- no pad menu --><% end %>
<%= render template: "layouts/application" %>

notejam/rubyonrails/notejam/app/views/pads/create.html.erb
<% content_for :page_title do %>New pad<% end %>

<%= form_for :pad do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= field_errors :name, @pad %>

  <%= f.submit "Create" %>
<% end %>

notejam/rubyonrails/notejam/app/views/pads/delete.html.erb
<% content_for :page_title do %><%= @pad.name %><% end %>

<p>Are you sure you want to delete <%= @pad.name %>?</p>
<%= form_for :pad do |f| %>
  <%= f.submit "Yes, I want to delete this pad", :class => "red" %>
  <%= link_to "Cancel", notes_path %>
<% end %>

notejam/rubyonrails/notejam/app/views/pads/edit.html.erb
<% content_for :page_title do %><%= @current_name %><% end %>

<%= form_for :pad do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= field_errors :name, @pad %>

  <%= f.submit "Save" %>
<% end %>

notejam/rubyonrails/notejam/app/views/pads/show.html.erb
<% content_for :page_title do %><%= @pad.name %> (<%= @notes.count %>)<% end %>
<% if @notes.count.nonzero? %>
  <table class="notes">
    <tr>
      <th class="note">Note <a href="<%= pad_path(:id => @pad.id) + "?order=name" %>" class="sort_arrow">↑</a><a href="<%= pad_path(:id => @pad.id) + "?order=-name" %>" class="sort_arrow">↓</a></th>
      <th class="date">Last modified <a href="<%= pad_path(:id => @pad.id) + "?order=updated_at" %>" class="sort_arrow">↑</a><a href="<%= pad_path(:id => @pad.id) + "?order=-updated_at" %>" class="sort_arrow">↓</a></th>
    </tr>
    <% @notes.each do |note| -%>
    <tr>
      <td><%= link_to note.name, note_path(:id => note.id) %></td>
      <td class="hidden-text date"><%= smart_date note.updated_at %></td>
    </tr>
    <% end -%>
  </table>
<% else %>
  <p class="empty">Create first note in the pad.</p>
<% end %>
<%= link_to "New note", create_note_path + "?pad=" + @pad.id.to_s, :class => "button" %>